// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/freshfield/FreshfieldDashboard.tsx": () => import("../components/mockups/freshfield/FreshfieldDashboard.tsx"),
  "./components/mockups/freshfield/FreshfieldLogin.tsx": () => import("../components/mockups/freshfield/FreshfieldLogin.tsx"),
  "./components/mockups/dashboard-redesign/CurrentDashboard.tsx": () => import("../components/mockups/dashboard-redesign/CurrentDashboard.tsx"),
  "./components/mockups/dashboard-redesign/CurrentLogin.tsx": () => import("../components/mockups/dashboard-redesign/CurrentLogin.tsx"),
  "./components/mockups/dashboard-redesign/RedesignDashboard.tsx": () => import("../components/mockups/dashboard-redesign/RedesignDashboard.tsx"),
  "./components/mockups/dashboard-redesign/RedesignLogin.tsx": () => import("../components/mockups/dashboard-redesign/RedesignLogin.tsx"),
  "./components/mockups/overhaul/OverhaulDashboard.tsx": () => import("../components/mockups/overhaul/OverhaulDashboard.tsx"),
  "./components/mockups/overhaul/OverhaulLogin.tsx": () => import("../components/mockups/overhaul/OverhaulLogin.tsx"),
  "./components/mockups/overhaul/StripeLogin.tsx": () => import("../components/mockups/overhaul/StripeLogin.tsx")
};
